apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'expo-module-gradle-plugin'

buildFeatures {
    buildConfig true
}

android {
    compileSdkVersion safeExtGet("compileSdkVersion", 35)
    defaultConfig {
        minSdkVersion safeExtGet("minSdkVersion", 24)
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.majorVersion
    }
    namespace "expo.modules.sshtransport"
}

dependencies {
    implementation 'com.github.mwiede:jsch:0.2.20'
}
