apply plugin: 'com.android.library'

group = 'host.exp.exponent'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()

android {
  namespace "expo.modules.sshtransport"
  buildFeatures {
    buildConfig true
  }
}

dependencies {
  implementation 'com.github.mwiede:jsch:0.2.20'
}
